export const initialState = {
  officers: [
    {
      id: 1,
      rank: "Colonel",
      name: "Nicholas Anthony",
      placesOfTreatment: {
        home: 0,
        hospital: 0,
        medPoint: 0,
      },
      diagnoses: [],
    },
    {
      id: 2,
      rank: "Lieutenant Colonel",
      name: "Archie Huber",
      placesOfTreatment: {
        home: 0,
        hospital: 0,
        medPoint: 0,
      },
      diagnoses: [],
    },
    {
      id: 3,
      rank: "Lieutenant Colonel",
      name: "Irving Brennan",
      placesOfTreatment: {
        home: 0,
        hospital: 0,
        medPoint: 0,
      },
      diagnoses: [],
    },
    {
      id: 4,
      rank: "Major",
      name: "Seth Bennett",
      placesOfTreatment: {
        home: 0,
        hospital: 0,
        medPoint: 0,
      },
      diagnoses: [],
    },
    {
      id: 5,
      rank: "Captain",
      name: "Dean Humphrey",
      placesOfTreatment: {
        home: 0,
        hospital: 0,
        medPoint: 0,
      },
      diagnoses: [],
    },
    {
      id: 6,
      rank: "Captain",
      name: "Derek Costa",
      placesOfTreatment: {
        home: 0,
        hospital: 0,
        medPoint: 0,
      },
      diagnoses: [],
    },
    {
      id: 7,
      rank: "First Lieutenant",
      name: "Tony Cohen",
      placesOfTreatment: {
        home: 0,
        hospital: 0,
        medPoint: 0,
      },
      diagnoses: [],
    },
    {
      id: 8,
      rank: "Second Lieutenant",
      name: "Oscar O'Donnell",
      placesOfTreatment: {
        home: 0,
        hospital: 0,
        medPoint: 0,
      },
      diagnoses: [],
    },
    {
      id: 9,
      rank: "Second Lieutenant",
      name: "Douglas Cook",
      placesOfTreatment: {
        home: 0,
        hospital: 0,
        medPoint: 0,
      },
      diagnoses: [],
    },
    {
      id: 10,
      rank: "Chief Warrant Officer 5",
      name: "Marcus Harvey",
      placesOfTreatment: {
        home: 0,
        hospital: 0,
        medPoint: 0,
      },
      diagnoses: [],
    },
    {
      id: 11,
      rank: "Chief Warrant Officer 5",
      name: "Matthew Harris",
      placesOfTreatment: {
        home: 0,
        hospital: 0,
        medPoint: 0,
      },
      diagnoses: [],
    },
    {
      id: 12,
      rank: "Chief Warrant Officer 3",
      name: "Geoffrey McKee",
      placesOfTreatment: {
        home: 0,
        hospital: 0,
        medPoint: 0,
      },
      diagnoses: [],
    },
  ],
  sergeants: [
    {
      id: 1,
      rank: "Command Sergeant Major",
      name: "Oscar McIntosh",
      placesOfTreatment: {
        home: 0,
        hospital: 0,
        medPoint: 0,
      },
      diagnoses: [],
    },
    {
      id: 2,
      rank: "Command Sergeant Major",
      name: "Peter Swenson",
      placesOfTreatment: {
        home: 0,
        hospital: 0,
        medPoint: 0,
      },
      diagnoses: [],
    },
    {
      id: 3,
      rank: "Sergeant Major",
      name: "Gavin Gonzalez",
      placesOfTreatment: {
        home: 0,
        hospital: 0,
        medPoint: 0,
      },
      diagnoses: [],
    },
    {
      id: 4,
      rank: "Sergeant Major",
      name: "Benjamin Conklin",
      placesOfTreatment: {
        home: 0,
        hospital: 0,
        medPoint: 0,
      },
      diagnoses: [],
    },
    {
      id: 5,
      rank: "Sergeant Major",
      name: "Levi Michael",
      placesOfTreatment: {
        home: 0,
        hospital: 0,
        medPoint: 0,
      },
      diagnoses: [],
    },
    {
      id: 6,
      rank: "First Sergeant",
      name: "William Mann",
      placesOfTreatment: {
        home: 0,
        hospital: 0,
        medPoint: 0,
      },
      diagnoses: [],
    },
    {
      id: 7,
      rank: "Master Sergeant",
      name: "Jonathon Proctor",
      placesOfTreatment: {
        home: 0,
        hospital: 0,
        medPoint: 0,
      },
      diagnoses: [],
    },
    {
      id: 8,
      rank: "Master Sergeant",
      name: "Jonathan Steele",
      placesOfTreatment: {
        home: 0,
        hospital: 0,
        medPoint: 0,
      },
      diagnoses: [],
    },
    {
      id: 9,
      rank: "Master Sergeant",
      name: "Derek Lawrence",
      placesOfTreatment: {
        home: 0,
        hospital: 0,
        medPoint: 0,
      },
      diagnoses: [],
    },
    {
      id: 10,
      rank: "Sergeant First Class",
      name: "Kenneth Pugh",
      placesOfTreatment: {
        home: 0,
        hospital: 0,
        medPoint: 0,
      },
      diagnoses: [],
    },
    {
      id: 11,
      rank: "Sergeant First Class",
      name: "Jason Stern",
      placesOfTreatment: {
        home: 0,
        hospital: 0,
        medPoint: 0,
      },
      diagnoses: [],
    },
    {
      id: 12,
      rank: "Staff Sergeant",
      name: "Alexander Mathews",
      placesOfTreatment: {
        home: 0,
        hospital: 0,
        medPoint: 0,
      },
      diagnoses: [],
    },
    {
      id: 13,
      rank: "Staff Sergeant",
      name: "ЛАСТАВЧУК Людмила В’ячеславівна",
      placesOfTreatment: {
        home: 0,
        hospital: 0,
        medPoint: 0,
      },
      diagnoses: [],
    },
    {
      id: 14,
      rank: "Staff Sergeant",
      name: "Martin Shafer",
      placesOfTreatment: {
        home: 0,
        hospital: 0,
        medPoint: 0,
      },
      diagnoses: [],
    },
  ],
  soldiers: [
    {
      id: 1,
      rank: "Specialist",
      name: "Brendan Mathis",
      placesOfTreatment: {
        home: 0,
        hospital: 0,
        medPoint: 0,
      },
      diagnoses: [],
    },
    {
      id: 2,
      rank: "Specialist",
      name: "Alec Wall",
      placesOfTreatment: {
        home: 0,
        hospital: 0,
        medPoint: 0,
      },
      diagnoses: [],
    },
    {
      id: 3,
      rank: "Corporal",
      name: "Brent Gentry",
      placesOfTreatment: {
        home: 0,
        hospital: 0,
        medPoint: 0,
      },
      diagnoses: [],
    },
    {
      id: 4,
      rank: "Corporal",
      name: "Dylan Ziegler",
      placesOfTreatment: {
        home: 0,
        hospital: 0,
        medPoint: 0,
      },
      diagnoses: [],
    },
    {
      id: 5,
      rank: "Corporal",
      name: "Tanner Kessler",
      placesOfTreatment: {
        home: 0,
        hospital: 0,
        medPoint: 0,
      },
      diagnoses: [],
    },
    {
      id: 7,
      rank: "Private First Class",
      name: "Antonio Kennedy",
      placesOfTreatment: {
        home: 0,
        hospital: 0,
        medPoint: 0,
      },
      diagnoses: [],
    },
    {
      id: 8,
      rank: "Private",
      name: "Jacob McCoy",
      placesOfTreatment: {
        home: 0,
        hospital: 0,
        medPoint: 0,
      },
      diagnoses: [],
    },
    {
      id: 9,
      rank: "Private",
      name: "James Bowers",
      placesOfTreatment: {
        home: 0,
        hospital: 0,
        medPoint: 0,
      },
      diagnoses: [],
    },
  ],
};
